version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football
    expose:
      - '3306'

  football-fixtures:
    image: football-fixtures
    container_name: football-fixtures-api
    build:
      context: .
      args:
        - COMMIT_HASH=COMMIT_HASH
      dockerfile: ./apps/football-fixtures/dockerfile
    environment:
      HOST: 127.0.0.1
      PORT: 4000
      NODE_ENV: production
      DB_NAME: football
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_TYPE: "mysql"
      DB_PORT: 3306
    ports:
      - 4000:3000
    depends_on:
      - mysql
