version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"

volumes:
  db_data: {}

